DROP TABLE IF EXISTS test;
CREATE TABLE newtable(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    a VARCHAR(255),
    b VARCHAR(255)
);

INSERT INTO test ( a, b ) VALUES ( 'NEW VALUE', 'NEW VALUE 2' );