SELECT P_CODE, P_DESCRIPT, P_QOH, P_MIN, P_PRICE 
FROM PRODUCT
WHERE P_CODE <'1558-QW1';

CREATE [UNIQUE] INDEX indexname ON tablename( column1 [, column2]);

SELECT <column(s)>
FROM <Table name>
WHERE <Conditions>; 

SELECT P_DESCRIPT, P_QOH, P_PRICE, P_QOH*P_PRICE AS TOTVALUE 
FROM PRODUCT;

DELETE FROM PRODUCT
WHERE P_CODE = 'BRT-345';

